### ISSUE TITLE
Add button dropdown does not appear

### ISSUE THREAD

**Issue by crispinh2o** [ging/fi-ware-idm-rails#14]
Within the div tabbable/users/add ... i do not operate the drop-down

![captura de pantalla 2013-07-22 a la s 12 39 13](https://f.cloud.github.com/assets/1405896/834310/fdbf3634-f2ba-11e2-972a-067f53708ebd.png)

**Comment by atd** [comment]
Take a look at the right of the div, a slide will probably appear
