### ISSUE TITLE
/user applications

### ISSUE THREAD

**Issue by crispinh2o** [ging/fi-ware-idm-rails#15]
see this box.. jaarrl

![captura de pantalla 2013-07-22 a la s 12 40 45](https://f.cloud.github.com/assets/1405896/834319/31571962-f2bb-11e2-99aa-97bf7ac9d050.png)

**Comment by atd** [comment]
I cannot reproduce this

**Comment by atd** [comment]
Maybe this is related to this commit https://github.com/ging/fi-ware-idm/blob/0ed4fe235580d6741db5b2731c18ee2301b9f877/app/views/site/clients/_client.html.erb
