### ISSUE TITLE
Missing /assets/icons&fonts/comfortaa_regular-webfont.woff

### ISSUE THREAD

**Issue by atd** [ging/fi-ware-idm-rails#17]

**Comment by atd** [comment]
It still shows up :grimacing: 

![image](https://f.cloud.github.com/assets/26228/857091/fe2a88d0-f549-11e2-81b9-8dd8b6d06255.png)

**Comment by crispinh2o** [comment]
thanks!!

**Comment by atd** [comment]
Still appearing :tired_face:

**Comment by crispinh2o** [comment]
I don´t know.. Only failure the format .woff.... The routes are equal!

Please, check it out today. I don´t have any error in the js console

![captura de pantalla 2013-07-29 a la s 02 50 59](https://f.cloud.github.com/assets/1405896/869180/10b23a1a-f7e9-11e2-9c08-f0b0a929b66f.png)

**Comment by crispinh2o** [comment]
Third time's a charm!!  
Thanks @atd
