### ISSUE TITLE
ActionView::MissingTemplate in Site/clients#edit

### ISSUE THREAD

**Issue by crispinh2o** [ging/fi-ware-idm-rails#18]
I can´t edit the application
![captura de pantalla 2013-07-24 a la s 00 41 16](https://f.cloud.github.com/assets/1405896/845492/14c54dbc-f3e9-11e2-83da-df081888368c.png)

**Comment by crispinh2o** [comment]
only when I´m switched to organization

**Comment by atd** [comment]
Please git-pull in social stream

**Comment by crispinh2o** [comment]
:dancers:
