### ISSUE TITLE
Copy client secret from application credentails is difficult

### ISSUE THREAD

**Issue by atd** [ging/fi-ware-idm-rails#3]
It is quite difficult to copy the Client Secret in the application's credentials dropdown

**Comment by crispinh2o** [comment]
Do you think it is a good idea to change carousel as more info on the user profile?

![captura de pantalla 2013-07-22 a la s 21 12 53](https://f.cloud.github.com/assets/1405896/837253/be617c3e-f302-11e2-89f7-4788a57339ed.png)
