### ISSUE TITLE
"active" class for <li>

### ISSUE THREAD

**Issue by crispinh2o** [ging/fi-ware-idm-rails#5]
example
   <li class="my-applications active">

![captura de pantalla 2013-07-16 a la s 02 03 30](https://f.cloud.github.com/assets/1405896/801802/45a46812-edab-11e2-9026-c69b0f70494f.png)

**Comment by crispinh2o** [comment]
It´s done, Thanks!!

**Comment by atd** [comment]
Please be aware that I added a new `<li class="members">` besides `<li class="organizations">` so probably the CSS will be broken

**Comment by crispinh2o** [comment]
; ) better!!

**Comment by crispinh2o** [comment]
The toolbar does not change when I open an application

![captura de pantalla 2013-07-22 a la s 20 35 44](https://f.cloud.github.com/assets/1405896/837044/90e1e306-f2fe-11e2-84cb-9818bff75d22.png)
