### ISSUE TITLE
Mails still using the old domain in the new instance

### ISSUE THREAD

**Issue by agordillo** [ging/fi-ware-idm-rails#59]
In the new instance: account.lab.fi-ware.eu, mails still using the idm.lab.fi-ware.eu domain instead of the appropiate one: account.lab.fi-ware.eu .

Thus, confirmation links are sent redirecting to idm.lab.fi-ware.eu instead of  account.lab.fi-ware.eu and so new accounts can't be confirmed and no new users can be created.

In the 'stable' branch, i changed all the references to idm.lab.fi-ware.eu to account.lab.fi-ware.eu, but this don't fix the issue.
It seems that modify the device gem initializer (config.mailer_sender = "no-reply@account.lab.fi-ware.eu") it's not enough.

**Comment by agordillo** [comment]
Fixed!

**Comment by dirkk0** [comment]
IMHO this address shouldn't be hardcoded, but rather configurable, so that this enabler works both in the FI-WARE and in any other context.

**Comment by atd** [comment]
Hi @dirkk0 this can be already achieved. I just uploaded an example 095cacff8e7c2b54c4f28543bf39e6ce97b9ae74

Just remove the `.example` of that file and change the settings you want.

**Comment by dirkk0** [comment]
Ah - I see, thank you!
