### ISSUE TITLE
Installation and configuration

### ISSUE THREAD

**Issue by dirkk0** [ging/fi-ware-idm-rails#66]
Hi,

is there any information on how to configure this?

From the issues I see that there are people using this and nobody had installation issues, so I it seems like I didn't find the correct document?

I think I installed it correctly (at least the server is running) and I saw from the travis file that I needed to create the database 'fi-ware-idm_development', but if I try to register I get the error:
`Table 'fi-ware-idm_development.users' doesn't exist: SHOW FULL FIELDS FROM 'users'`
My guess is that I have to initialize the tables, but how?

Thanks in advance,
  Dirk

**Comment by atd** [comment]
Hi @dirkk0 did you already take a look to https://github.com/ging/fi-ware-idm/wiki/Installation-guide ?

**Comment by dirkk0** [comment]
Nope, I didn't - thanks for the hint!

I had to do more than `git clone`though. For example I needed to install ImageMagick. So I fear that this page isn't complete?

I am not familiar with capistrano, but: since I installed the application directly on EC2 - do I need it?  Or is doing the database initialization?

Again, thanks for your answer.

**Comment by dirkk0** [comment]
Does anyone know what else is needed?
I have the rails app up and running, and I see the splash screen with the login. Just every attempt to do something beyond gives me the database error above.

**Comment by atd** [comment]
Hi @dirkk0, you need to load the database schema. Please try:

`rake db:schema:load`

However, be aware that Rails has production, test and development environments. Install instructions are described for a production environment.

You can find further information about Rails at http://guides.rubyonrails.org/v3.2.14/

**Comment by dirkk0** [comment]
It works now - thank you!

As you can see I am a rails noob, so - sorry for taking your time.
But that command was the missing link. I will post my installation bash, if that is ok with you.

Best,
  Dirk

**Comment by atd** [comment]
Great! Feel free to improve the documentation. It will help others for sure

**Comment by dirkk0** [comment]
This here should work: https://gist.github.com/dirkk0/7377880
