### ISSUE TITLE
Edit and delete buttons are not visible anymore

### ISSUE THREAD

**Issue by atd** [ging/fi-ware-idm-rails#68]
The pen and the trash buttons should be visible for custom roles. Now they only show up when hovering on them.

![image](https://f.cloud.github.com/assets/26228/1523399/b362c4bc-4bb5-11e3-8dae-632260966a66.png)

**Comment by crispinh2o** [comment]
79fb1ca2288f8d933ebf3ac0c46fe4073f2761f8
