### ISSUE TITLE
/applications/ edit & create

### ISSUE THREAD

**Issue by crispinh2o** [ging/fi-ware-idm-rails#9]
The accordion that i should only appear when the application software. This created and we are going to edit it. \* Here copy the code to delete account in the settings.

![captura de pantalla 2013-07-22 a la s 12 26 14](https://f.cloud.github.com/assets/1405896/834246/2a044ca4-f2b9-11e2-839e-182c1e08ad1c.png)

**Comment by atd** [comment]
Partial implemented in 67b4701d22b0ff861c8b5256215c88339d0f5c6c
